import pandas as pd
import numpy as np
import joblib
import os
import sys

# Add backend directory to sys path so we can import app.ml
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from app.ml.preprocessing import CleaningTransformer, OutlierTransformer, TimeFeatureExtractor, LagRollingFeatureExtractor, InventoryPriceFeatureExtractor

def run_pipeline(data_path='data/raw/mock_sales_data.csv', output_dir='data/processed', model_dir='app/ml/models'):
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(model_dir, exist_ok=True)
    
    print(f"Loading data from {data_path}...")
    df = pd.read_csv(data_path)
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Sort to ensure time series properties hold
    df = df.sort_values(by=['Store_ID', 'Product_ID', 'Date']).reset_index(drop=True)
    
    # Chronological train/test split to avoid data leakage
    # We will use the last 30 days as a test set for demonstration
    split_date = df['Date'].max() - pd.Timedelta(days=30)
    train_df = df[df['Date'] < split_date].copy()
    test_df = df[df['Date'] >= split_date].copy()
    
    print(f"Train size: {len(train_df)}, Test size: {len(test_df)}")
    
    # 1. Base Pipeline (Cleaning, Outliers, Feature Engineering)
    # These operations apply to the whole dataframe and generate new columns
    base_pipeline = Pipeline([
        ('cleaner', CleaningTransformer()),
        ('outliers', OutlierTransformer(columns=['Sales', 'Inventory', 'Temperature', 'Rainfall'])),
        ('time_features', TimeFeatureExtractor()),
        ('lag_rolling', LagRollingFeatureExtractor()),
        ('inventory_price', InventoryPriceFeatureExtractor())
    ])
    
    print("Fitting base pipeline on train data...")
    train_transformed = base_pipeline.fit_transform(train_df)
    
    print("Transforming test data...")
    test_transformed = base_pipeline.transform(test_df)
    
    # We need to handle categorical encoding as a final step
    # After the base pipeline, we drop NA generated by lags (or fill them)
    train_transformed = train_transformed.fillna(0)
    test_transformed = test_transformed.fillna(0)
    
    categorical_cols = ['Store_ID', 'Product_ID', 'Category']
    numeric_cols = [c for c in train_transformed.columns if c not in categorical_cols and c != 'Date']
    
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols),
            ('num', 'passthrough', numeric_cols) # Pass through the numeric features unchanged
        ]
    )
    
    final_pipeline = Pipeline([
        ('preprocessor', preprocessor)
    ])
    
    print("Fitting final categorical encoder pipeline...")
    final_train_array = final_pipeline.fit_transform(train_transformed)
    final_test_array = final_pipeline.transform(test_transformed)
    
    # Get column names after OHE
    cat_feature_names = final_pipeline.named_steps['preprocessor'].transformers_[0][1].get_feature_names_out(categorical_cols)
    final_columns = list(cat_feature_names) + numeric_cols
    
    final_train_df = pd.DataFrame(final_train_array, columns=final_columns)
    final_test_df = pd.DataFrame(final_test_array, columns=final_columns)
    
    # Add date back for reference if needed
    final_train_df['Date'] = train_transformed['Date'].values
    final_test_df['Date'] = test_transformed['Date'].values
    
    print("Saving processed data...")
    final_train_df.to_csv(f"{output_dir}/train_processed.csv", index=False)
    final_test_df.to_csv(f"{output_dir}/test_processed.csv", index=False)
    
    print("Saving pipeline objects...")
    joblib.dump(base_pipeline, f"{model_dir}/base_feature_pipeline.joblib")
    joblib.dump(final_pipeline, f"{model_dir}/final_encoder_pipeline.joblib")
    
    print(f"Data processing complete! Processed files saved in {output_dir}")
    print(f"Pipelines saved in {model_dir}")

if __name__ == "__main__":
    run_pipeline()
